/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho_labprog3_3;

import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mattheus
 */
public class JanelaTarefa extends javax.swing.JFrame {

    Integer idProjeto;
    Integer idTarefaAtual;
    Integer idPessoa;
    List<Tarefa> tarefas;
    List<Pessoa> pessoas;
    List<Projeto> projetos;

    public void inicializar() throws Exception {

        projetos = new ArrayList<>();
        ProjetoDAO daoProjeto = new ProjetoDAOJDBC();
        projetos = daoProjeto.listar();
        lstProjetos.setModel(new ProjetoListModel(projetos));
        lstProjetos.updateUI();

        pessoas = new ArrayList<>();
        PessoaDAO daoPessoa = new PessoaDAOJDBC();
        pessoas = daoPessoa.listar();
        lstTodasPessoas.setModel(new PessoaListModel(pessoas));
        lstTodasPessoas.updateUI();

    }

    public JanelaTarefa() throws Exception {
        initComponents();
        inicializar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstTodasPessoas = new javax.swing.JList<>();
        btnCadastrarPessoa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProjetos = new javax.swing.JList<>();
        btnCadastrarProjeto = new javax.swing.JButton();
        txtNomePessoa = new javax.swing.JTextField();
        txtTipoProjeto = new javax.swing.JTextField();
        txtNomeProjeto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstTarefasRequisitos = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstTarefas = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        btnAdicionarTarefaRequisito = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstPessoasTarefas = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtDuracaoTarefa = new javax.swing.JTextField();
        txtDescricaoTarefa = new javax.swing.JTextField();
        txtPercentualTarefa = new javax.swing.JTextField();
        btnCriarTarefa = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnDetalhes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnTodasTarefas = new javax.swing.JButton();
        btnTarefasConcluidas = new javax.swing.JButton();
        btnTarefasIniciaveis = new javax.swing.JButton();
        btnTarefasPorFazer = new javax.swing.JButton();
        btnListarPessoasTarefas = new javax.swing.JButton();
        btnAdicionarPessoaTarefa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtDescricaoEditar = new javax.swing.JTextField();
        txtDuracaoEditar = new javax.swing.JTextField();
        txtPercentualEditar = new javax.swing.JTextField();
        txtStatusEditar = new javax.swing.JTextField();
        btnAlterarTarefa = new javax.swing.JButton();
        btnAtualizarDataFinal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        lstTodasPessoas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstTodasPessoas);

        btnCadastrarPessoa.setText("Cadastrar");
        btnCadastrarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPessoaActionPerformed(evt);
            }
        });

        lstProjetos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstProjetos);

        btnCadastrarProjeto.setText("Cadastrar");
        btnCadastrarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProjetoActionPerformed(evt);
            }
        });

        txtNomePessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePessoaActionPerformed(evt);
            }
        });

        txtTipoProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoProjetoActionPerformed(evt);
            }
        });

        txtNomeProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProjetoActionPerformed(evt);
            }
        });

        jLabel1.setText("Pessoas");

        jLabel2.setText("Projetos");

        lstTarefasRequisitos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(lstTarefasRequisitos);

        lstTarefas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(lstTarefas);

        jLabel4.setText("Requisitos");

        btnAdicionarTarefaRequisito.setText("Adicionar Tarefa como Requisito");
        btnAdicionarTarefaRequisito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarTarefaRequisitoActionPerformed(evt);
            }
        });

        lstPessoasTarefas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(lstPessoasTarefas);

        jLabel5.setText("Pessoas Trabalhando nessa tarefa");

        jLabel6.setText("Nome:");

        jLabel7.setText("Nome:");

        jLabel8.setText("Tipo:");

        txtDescricaoTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoTarefaActionPerformed(evt);
            }
        });

        btnCriarTarefa.setText("Criar Tarefa");
        btnCriarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarTarefaActionPerformed(evt);
            }
        });

        jLabel9.setText("Criar Tarefa");

        jLabel10.setText("Descrição:");

        jLabel11.setText("Duração Esperada:");

        jLabel12.setText("Percentual:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCriarTarefa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescricaoTarefa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPercentualTarefa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDuracaoTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuracaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPercentualTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(63, 63, 63)
                .addComponent(btnCriarTarefa)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnDetalhes.setText("Detalhes");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        jLabel3.setText("Tarefas");

        btnTodasTarefas.setText("Todas as Tarefas");
        btnTodasTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodasTarefasActionPerformed(evt);
            }
        });

        btnTarefasConcluidas.setText("Tarefas Concluídas");
        btnTarefasConcluidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarefasConcluidasActionPerformed(evt);
            }
        });

        btnTarefasIniciaveis.setText("Tarefas Iniciáveis");
        btnTarefasIniciaveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarefasIniciaveisActionPerformed(evt);
            }
        });

        btnTarefasPorFazer.setText("Tarefas por Fazer");
        btnTarefasPorFazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarefasPorFazerActionPerformed(evt);
            }
        });

        btnListarPessoasTarefas.setText("Listar Pessoas");
        btnListarPessoasTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPessoasTarefasActionPerformed(evt);
            }
        });

        btnAdicionarPessoaTarefa.setText("Adicionar Pessoa");
        btnAdicionarPessoaTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPessoaTarefaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTarefasPorFazer, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTarefasIniciaveis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTodasTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTarefasConcluidas, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnListarPessoasTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionarPessoaTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTodasTarefas)
                    .addComponent(btnTarefasConcluidas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTarefasIniciaveis)
                    .addComponent(btnTarefasPorFazer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarPessoasTarefas)
                    .addComponent(btnAdicionarPessoaTarefa))
                .addContainerGap())
        );

        jLabel15.setText("Editar Tarefa");

        jLabel16.setText("Descrição:");

        jLabel17.setText("Duração Esperada:");

        jLabel18.setText("Percentual:");

        jLabel21.setText("Status:");

        txtDescricaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoEditarActionPerformed(evt);
            }
        });

        txtStatusEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusEditarActionPerformed(evt);
            }
        });

        btnAlterarTarefa.setText("Editar");
        btnAlterarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarTarefaActionPerformed(evt);
            }
        });

        btnAtualizarDataFinal.setText("Atualizar Data Final");
        btnAtualizarDataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarDataFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricaoEditar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDuracaoEditar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPercentualEditar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAlterarTarefa))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStatusEditar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnAtualizarDataFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDescricaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtDuracaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtPercentualEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(btnAtualizarDataFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtStatusEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnAlterarTarefa)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomePessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastrarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeProjeto)
                            .addComponent(txtTipoProjeto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCadastrarProjeto))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionarTarefaRequisito))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCadastrarPessoa)
                                        .addComponent(txtNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6))
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTipoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCadastrarProjeto)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnDetalhes))
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionarTarefaRequisito)
                            .addComponent(jLabel4))
                        .addGap(239, 239, 239)))
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomePessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePessoaActionPerformed

    private void btnTarefasConcluidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarefasConcluidasActionPerformed
        if (!lstProjetos.isSelectionEmpty()) {

            try {
                idProjeto = lstProjetos.getSelectedValue().getId();
                tarefas = new ArrayList<>();

                TarefaDAO dao = new TarefaDAOJDBC();
                tarefas = dao.listarTarefasConcluidas(idProjeto);
                lstTarefas.setModel(new TarefaListModel(tarefas));

            } catch (Exception ex) {
                Logger.getLogger(JanelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnTarefasConcluidasActionPerformed

    private void txtTipoProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoProjetoActionPerformed

    private void btnTodasTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodasTarefasActionPerformed
        if (!lstProjetos.isSelectionEmpty()) {
            try {
                idProjeto = lstProjetos.getSelectedValue().getId();
                tarefas = new ArrayList<>();

                TarefaDAO dao = new TarefaDAOJDBC();
                tarefas = dao.listarTarefasProjeto(idProjeto);
                lstTarefas.setModel(new TarefaListModel(tarefas));
                lstTarefas.updateUI();

            } catch (Exception ex) {
                Logger.getLogger(JanelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_btnTodasTarefasActionPerformed

    private void txtNomeProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProjetoActionPerformed

    private void btnAdicionarPessoaTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPessoaTarefaActionPerformed
        if (!lstTodasPessoas.isSelectionEmpty() && !lstTarefas.isSelectionEmpty()) {
            idPessoa = lstProjetos.getSelectedValue().getId();
            idTarefaAtual = lstTarefas.getSelectedValue().getId();

            try {
                TarefaDAO dao = new TarefaDAOJDBC();
                dao.cadastrarPessoa(idTarefaAtual, idPessoa);
                lstPessoasTarefas.updateUI();
            } catch (Exception ex) {
                Logger.getLogger(JanelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAdicionarPessoaTarefaActionPerformed

    private void btnListarPessoasTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPessoasTarefasActionPerformed
        if (!lstProjetos.isSelectionEmpty() && !lstTarefas.isSelectionEmpty()) {

            idProjeto = lstProjetos.getSelectedValue().getId();
            pessoas = new ArrayList<>();
            idTarefaAtual = lstTarefas.getSelectedValue().getId();
            try {
                TarefaDAO dao = new TarefaDAOJDBC();
                pessoas = dao.listarPessoaTarefa(idTarefaAtual);
                lstPessoasTarefas.setModel(new PessoaListModel(pessoas));
                lstPessoasTarefas.updateUI();

            } catch (Exception ex) {
                Logger.getLogger(JanelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnListarPessoasTarefasActionPerformed

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        if (!lstTarefas.isSelectionEmpty()) {

            idTarefaAtual = lstTarefas.getSelectedValue().getId();
            System.out.println(idTarefaAtual);

            try {
                TarefaDAO dao = new TarefaDAOJDBC();
                Tarefa t = new Tarefa();
                t = dao.selecionarTarefa(idTarefaAtual);
                //t = lstTarefas.getSelectedValue();

                JOptionPane.showMessageDialog(null,
                        "Descrição: " + t.getDescricao() + "\n"
                        + "Duração Esperada: " + t.getDuracao_esperada() + "\n"
                        + "Percentual: " + t.getPercentual() + "\n"
                        + "Data de Início: " + t.getData_inicio() + "\n"
                        + "Data de Natal: " + t.getData_final() + "\n",
                        "Detalhes", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                Logger.getLogger(JanelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDetalhesActionPerformed

    private void btnTarefasPorFazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarefasPorFazerActionPerformed
        if (!lstProjetos.isSelectionEmpty()) {
            idProjeto = lstProjetos.getSelectedValue().getId();
            tarefas = new ArrayList<>();

            try {
                TarefaDAO dao = new TarefaDAOJDBC();
                tarefas = dao.listarTarefasPorFazer(idProjeto);
                lstTarefas.setModel(new TarefaListModel(tarefas));
                lstTarefas.updateUI();

            } catch (Exception ex) {
                Logger.getLogger(JanelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnTarefasPorFazerActionPerformed

    private void btnTarefasIniciaveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarefasIniciaveisActionPerformed
        if (!lstProjetos.isSelectionEmpty() && !lstTarefas.isSelectionEmpty()) {
            idProjeto = lstProjetos.getSelectedValue().getId();
            tarefas = new ArrayList<>();
            idTarefaAtual = lstTarefas.getSelectedValue().getId();
            try {
                TarefaDAO dao = new TarefaDAOJDBC();
                tarefas = dao.listarTarefasIniciaveis(idProjeto, idTarefaAtual);
                lstTarefasRequisitos.setModel(new TarefaListModel(tarefas));
                lstTarefasRequisitos.updateUI();
            } catch (Exception ex) {
                Logger.getLogger(JanelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnTarefasIniciaveisActionPerformed

    private void btnAdicionarTarefaRequisitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTarefaRequisitoActionPerformed
        if (!lstProjetos.isSelectionEmpty() && !lstTarefas.isSelectionEmpty()) {
            idProjeto = lstProjetos.getSelectedValue().getId();
            tarefas = new ArrayList<>();
            idTarefaAtual = lstTarefas.getSelectedValue().getId();
            try {
                TarefaDAO dao = new TarefaDAOJDBC();
                tarefas = dao.listarTarefasRequisito(idProjeto, idTarefaAtual);
                lstTarefasRequisitos.setModel(new TarefaListModel(tarefas));
                lstTarefasRequisitos.updateUI();
            } catch (Exception ex) {
                Logger.getLogger(JanelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnAdicionarTarefaRequisitoActionPerformed

    private void btnCadastrarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPessoaActionPerformed
        if (!txtNomePessoa.getText().isEmpty()) {

            try {
                List<Pessoa> pessoas = new ArrayList<>();
                PessoaDAO dao = new PessoaDAOJDBC();
                Pessoa p = new Pessoa();
                p.setNome(txtNomePessoa.getText());
                dao.criar(p);
                pessoas = dao.listar();

                lstTodasPessoas.setModel(new PessoaListModel(pessoas));
                lstTodasPessoas.updateUI();
            } catch (Exception ex) {
                Logger.getLogger(JanelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnCadastrarPessoaActionPerformed

    private void btnCadastrarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProjetoActionPerformed
        if (!txtNomeProjeto.getText().isEmpty() && !txtTipoProjeto.getText().isEmpty()) {
            try {
                projetos = new ArrayList<>();
                ProjetoDAO dao = new ProjetoDAOJDBC();
                Projeto p = new Projeto();
                p.setNome(txtNomeProjeto.getText());
                p.setTipo(txtTipoProjeto.getText());
                dao.criar(p);

                projetos = dao.listar();

                lstProjetos.setModel(new ProjetoListModel(projetos));
                lstProjetos.updateUI();
            } catch (Exception ex) {
                Logger.getLogger(JanelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCadastrarProjetoActionPerformed

    private void btnCriarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarTarefaActionPerformed
        if (!txtDescricaoTarefa.getText().isEmpty() && !txtDuracaoTarefa.getText().isEmpty()
                && !txtPercentualTarefa.getText().isEmpty() && !lstProjetos.isSelectionEmpty()) {

            try {
                idProjeto = lstProjetos.getSelectedValue().getId();
                TarefaDAO dao = new TarefaDAOJDBC();
                Tarefa t = new Tarefa();
                t.setDescricao(txtDescricaoTarefa.getText());
                t.setDuracao_esperada(Integer.parseInt(txtDuracaoTarefa.getText()));
                t.setPercentual(Double.parseDouble(txtPercentualTarefa.getText()));
                t.setID_Projeto(idProjeto);
                dao.criarTarefa(t, idProjeto);

                tarefas = dao.listarTarefasProjeto(idProjeto);

                lstTarefas.setModel(new TarefaListModel(tarefas));
            } catch (Exception ex) {
                Logger.getLogger(JanelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCriarTarefaActionPerformed

    private void txtDescricaoTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoTarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoTarefaActionPerformed

    private void txtDescricaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoEditarActionPerformed

    private void txtStatusEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusEditarActionPerformed

    private void btnAlterarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarTarefaActionPerformed
        if (!lstTarefas.isSelectionEmpty()) {
            /*!txtDescricaoEditar.getText().isEmpty() && !txtDuracaoEditar.getText().isEmpty()
                && txtPercentualEditar.getText().isEmpty() && txtDataInicioEditar.getText().isEmpty()
                && txtDataFimEditar.getText().isEmpty()&& txtStatusEditar.getText().isEmpty() */
            try {
                idTarefaAtual = lstTarefas.getSelectedValue().getId();
                Tarefa t = new Tarefa();
                TarefaDAO dao = new TarefaDAOJDBC();

                if (!txtDescricaoEditar.getText().isEmpty()) {
                    t.setDescricao(txtDescricaoEditar.getText());
                    dao.atualizarTarefaDescricao(idTarefaAtual, t.getDescricao());
                }

                if (!txtDuracaoEditar.getText().isEmpty()) {
                    t.setDuracao_esperada(Integer.parseInt(txtDuracaoEditar.getText()));
                    dao.atualizarTarefaDuracaoEsperada(idTarefaAtual, t.getDuracao_esperada());
                }

                if (txtPercentualEditar.getText().isEmpty()) {
                    t.setPercentual(Double.parseDouble(txtPercentualEditar.getText()));
                    dao.atualizarTarefaPercentual(idTarefaAtual, t.getPercentual());

                }

                if (txtStatusEditar.getText().isEmpty()) {
                    t.setStatus(Integer.parseInt(txtStatusEditar.getText()));
                    dao.atualizarTarefaStatus(idTarefaAtual, t.getStatus());

                }

            } catch (Exception ex) {
                Logger.getLogger(JanelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_btnAlterarTarefaActionPerformed

    private void btnAtualizarDataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarDataFinalActionPerformed
        if (!lstTarefas.isSelectionEmpty()) {
            idTarefaAtual = lstTarefas.getSelectedValue().getId();
            try {
                TarefaDAO dao = new TarefaDAOJDBC();
                dao.atualizarTarefaDataFim(idTarefaAtual);
            } catch (Exception ex) {
                Logger.getLogger(JanelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_btnAtualizarDataFinalActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPessoaTarefa;
    private javax.swing.JButton btnAdicionarTarefaRequisito;
    private javax.swing.JButton btnAlterarTarefa;
    private javax.swing.JButton btnAtualizarDataFinal;
    private javax.swing.JButton btnCadastrarPessoa;
    private javax.swing.JButton btnCadastrarProjeto;
    private javax.swing.JButton btnCriarTarefa;
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnListarPessoasTarefas;
    private javax.swing.JButton btnTarefasConcluidas;
    private javax.swing.JButton btnTarefasIniciaveis;
    private javax.swing.JButton btnTarefasPorFazer;
    private javax.swing.JButton btnTodasTarefas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<Pessoa> lstPessoasTarefas;
    private javax.swing.JList<Projeto> lstProjetos;
    private javax.swing.JList<Tarefa> lstTarefas;
    private javax.swing.JList<Tarefa> lstTarefasRequisitos;
    private javax.swing.JList<Pessoa> lstTodasPessoas;
    private javax.swing.JTextField txtDescricaoEditar;
    private javax.swing.JTextField txtDescricaoTarefa;
    private javax.swing.JTextField txtDuracaoEditar;
    private javax.swing.JTextField txtDuracaoTarefa;
    private javax.swing.JTextField txtNomePessoa;
    private javax.swing.JTextField txtNomeProjeto;
    private javax.swing.JTextField txtPercentualEditar;
    private javax.swing.JTextField txtPercentualTarefa;
    private javax.swing.JTextField txtStatusEditar;
    private javax.swing.JTextField txtTipoProjeto;
    // End of variables declaration//GEN-END:variables
}
